from django.db import models

# Create your models here.
class Squirrels(models.Model):
    Latitude = models.DecimalField(decimal_places=10, max_digits=21, default=' ')
    Longitude = models.DecimalField(decimal_places=10, max_digits=20, default=' ')
    Unique_Squirrel_ID = models.TextField(primary_key=True, default=' ')
    # Unique_Squirrel_ID = models.TextField(max_length=15, default=' ')
    Shift = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Date = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Age = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Primary_Fur_Color = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Location = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Specific_Location = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Running = models.BooleanField(null=True, blank=True,default=False)
    Chasing = models.BooleanField(null=True, blank=True,default=False)
    Climbing = models.BooleanField(null=True, blank=True,default=False)
    Eating = models.BooleanField(null=True, blank=True,default=False)
    Foraging = models.BooleanField(null=True, blank=True,default=False)
    Other_Activities = models.CharField(max_length=100, null=True, blank=True, default=' ')
    Kuks = models.BooleanField(null=True, blank=True,default=False)
    Quaas = models.BooleanField(null=True, blank=True,default=False)
    Moans = models.BooleanField(null=True, blank=True,default=False)
    Tail_flags = models.BooleanField(null=True, blank=True,default=False)
    Tail_twitches = models.BooleanField(null=True, blank=True,default=False)
    Approaches = models.BooleanField(null=True, blank=True,default=False)
    Indifferent = models.BooleanField(null=True, blank=True,default=False)
    Runs_from = models.BooleanField(null=True, blank=True,default=False)